CREATE TABLE projects (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  base_url VARCHAR(2048) NOT NULL,
  description TEXT NULL,
  tags JSON NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  check_interval INT UNSIGNED NOT NULL COMMENT 'seconds',
  timeout INT UNSIGNED NOT NULL COMMENT 'seconds',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_projects_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
